// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Build the Prisma datasource URL from the same MYSQL_* vars used by paf-admin,
// so a single .env works for both services.
const host = process.env.MYSQL_HOST ?? "localhost";
const port = process.env.MYSQL_PORT ?? "3306";
const user = process.env.MYSQL_USER ?? "";
const password = process.env.MYSQL_PASSWORD ?? "";
const database = process.env.MYSQL_DB_NAME ?? "";
const url =
  process.env.DATABASE_URL ??
  `mysql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${database}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: { url },
});
