apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service
data:
  APP_URL: "gateway.pa-f.net"
  DATABASE_URL: "${AUTH_SERVICE_DATABASE_URL}"
  DATABASE_USER: "${AUTH_SERVICE_DATABASE_USER}"
  DATABASE_PASSWORD: "${AUTH_SERVICE_DATABASE_PASSWORD}"
  DATABASE_NAME: "${AUTH_SERVICE_DATABASE_NAME}"
  DATABASE_HOST: "mysql"
  DATABASE_PORT: "3306"
  OAUTH_CODES_SECRET: "${AUTH_SERVICE_OAUTH_CODES_SECRET}"